---


- name: install vault password file
  copy:
    content: '{{ configure_ansible_vault_password }}'
    dest: '{{ configure_ansible_vault_password_file.path|default("/etc/ansible/.vpf") }}'
    owner: '{{ configure_ansible_vault_password_file.owner|default("root") }}'
    group: '{{ configure_ansible_vault_password_file.group|default("root") }}'
    mode: '{{ configure_ansible_vault_password_file.permissions|default("0640") }}'
  when: configure_ansible_vault_password is defined
  no_log: true

- name: ensure ansible is configured
  template: 
    src: 'ansible.cfg.j2' 
    dest: '{{ configure_ansible_config_directory }}/ansible.cfg'
  become: true