---

- name: install apt packages
  apt: 
    name: '{{ item }}'
    state: present 
    update_cache: true
  with_items: '{{ configure_self_install_apt }}'
  become: true

- name: install python libraries
  pip: 
    name: '{{ item }}'
  with_items: '{{ configure_self_install_pip }}'
  become: true