---

- name: install apt packages
  apt: 
    name: '{{ item }}'
    state: present 
    update_cache: true
    cache_valid_time: 3600
  with_items: '{{ configure_ansible_install_apt }}'
  become: true

- name: install python libraries
  pip: 
    name: '{{ item }}'
  with_items: '{{ configure_ansible_install_pip }}'
  become: true